// {data.results.map(element => {
//     return (
//       <Luke
//         key={element.height}
//         name={element.name}
//         hairColor={element.hair_color}
//       />
//       <C-3PO
//         key={element.height}
//         name={element.name}
//         hairColor={element.hair_color}
//       />
//       <R2-D2
//         key={element.height}
//         name={element.name}
//         hairColor={element.hair_color}
//       />
//       <DarthVader
//         key={element.height}
//         name={element.name}
//         hairColor={element.hair_color}
//       />
//       <Leia
//         key={element.height}
//         name={element.name}
//         hairColor={element.hair_color}
//       />
//       <Owen
//         key={element.height}
//         name={element.name}
//         hairColor={element.hair_color}
//       />
//       <Beru
//         key={element.height}
//         name={element.name}
//         hairColor={element.hair_color}
//       />
//       <R5-D4
//         key={element.height}
//         name={element.name}
//         hairColor={element.hair_color}
//       />
//       <Biggs
//         key={element.height}
//         name={element.name}
//         hairColor={element.hair_color}
//       />
//       <ObiWan
//         key={element.height}
//         name={element.name}
//         hairColor={element.hair_color}
//       />
//     );
//   })}